nginx:
    build: ./nginx/
    ports:
        - 8081:80
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php/
    expose:
        - 9000
    links:
        - postgres
    volumes_from:
        - app

app:
    image: php:7.0-fpm
    volumes:
        - .:/var/www/html
    command: "true"

postgres:
    build: ./postgres/
    volumes_from:
        - data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project

data:
    build: ./postgres/
    volumes:
      - /var/lib/postgresql/data
    command: "true"

composer:
    entrypoint: /bin/true
    restart: 'no'
    build: ./composer/
    command: install --working-dir=/var/www/html
    volumes_from:
      - app